version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres
    environment:
      POSTGRES_DB: rag_system
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - rag-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag_user -d rag_system"]
      interval: 10s
      timeout: 5s
      retries: 5

  vllm:
    image: vllm/vllm-openai:latest
    container_name: rag-vllm
    command: [
      "--model", "BAAI/bge-large-en-v1.5",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--max-model-len", "8192",
      "--gpu-memory-utilization", "0.9",
      "--dtype", "auto",
      "--enforce-eager",
      "--enable-prefix-caching"
    ]
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '8gb'
    ipc: host
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    profiles:
      - gpu

  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  rag-network:
    driver: bridge

volumes:
  postgres_data:
  huggingface_cache:
  ollama_models: